# Generated by Django 4.1.6 on 2023-03-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_product_discontinued_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='external_ref',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='poll_url',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('INITIATED', 'Initiated'), ('CANCELLED', 'Cancelled')], max_length=10),
        ),
    ]
