# Generated by Django 4.1.6 on 2023-03-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_external_ref_alter_payment_poll_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REFUNDED', 'Refunded'), ('INITIATED', 'Initiated'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], max_length=10),
        ),
    ]
