# Generated by Django 4.1.6 on 2023-03-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REFUNDED', 'Refunded'), ('INITIATED', 'Initiated'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], max_length=10),
        ),
    ]
