# Generated by Django 4.1.6 on 2023-03-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_mobile_wallet_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='external_ref',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mobile_wallet_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
