# Generated by Django 4.1.6 on 2023-03-01 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_remaining', models.IntegerField(default=0)),
                ('chat_max_tokens', models.IntegerField(default=150)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TokenReload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaded', models.BooleanField(default=False)),
                ('load_timestamp', models.DateTimeField(default=None, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='payments.payment')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='payments.product')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zimgpt.profile')),
            ],
        ),
        migrations.CreateModel(
            name='APIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('CHAT', 'CHAT'), ('ANS', 'ANSWERS')], max_length=50)),
                ('prompt', models.TextField()),
                ('prompt_tokens', models.IntegerField()),
                ('tokens_used', models.IntegerField()),
                ('tokens_remaining', models.IntegerField()),
                ('ai_model', models.CharField(max_length=256)),
                ('response_text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zimgpt.profile')),
            ],
        ),
    ]
