# Generated by Django 4.1.6 on 2023-03-02 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_status'),
        ('zimgpt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenreload',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payments.product'),
        ),
    ]
