# Generated by Django 4.1.6 on 2023-03-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zimgpt', '0002_alter_tokenreload_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wa_chat_state',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='chat_max_tokens',
            field=models.IntegerField(default=4000),
        ),
    ]
