# Generated by Django 4.1.6 on 2023-04-10 07:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('zimgpt', '0003_profile_wa_chat_state_alter_profile_chat_max_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ref',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wa_chat_state',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
