# Generated by Django 4.1.6 on 2023-04-28 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zimgpt', '0005_alter_profile_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_engagement',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='low_bal_last_notified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='notified_low_bal',
            field=models.IntegerField(default=0),
        ),
    ]
