# Generated by Django 4.1.6 on 2023-04-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zimgpt', '0006_profile_last_engagement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('daily_active_users', models.IntegerField()),
                ('daily_new_users', models.IntegerField()),
                ('daily_token_purchases', models.IntegerField()),
                ('daily_token_purchase_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('daily_api_requests', models.IntegerField()),
                ('daily_token_usage', models.IntegerField()),
                ('total_users', models.IntegerField()),
            ],
        ),
    ]
