# Generated by Django 4.1.6 on 2023-05-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zimgpt', '0007_dailymetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stop_promotions',
            field=models.BooleanField(default=False),
        ),
    ]
