# Generated by Django 4.1.6 on 2023-05-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_accounts', '0002_alter_pfitzuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfitzuser',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='pfitzuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
    ]
