# Generated by Django 4.1.6 on 2023-05-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0005_alter_pfitzuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pfitzuser',
            options={},
        ),
    ]
